function formating_help --description "Show usage examples for formating functions"
    echo ""
    echo "📋 Formating Functions - Usage Guide"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Available Functions:"
    echo ""
    echo "  ✅ success \"message\"   - Print success message in green"
    echo "  ⚠️  warning \"message\"   - Print warning message in yellow"
    echo "  ❌ error \"message\"     - Print error message in red"
    echo "  🎨 formating type \"msg\" - Format text by type"
    echo ""
    echo "Examples:"
    echo ""
    echo "  # Direct usage:"
    echo -e "  \033[1;32msuccess \"Operation completed!\"\033[0m"
    echo -e "  \033[1;33mwarning \"Be careful with this action\"\033[0m"
    echo -e "  \033[1;31merror \"Something went wrong!\"\033[0m"
    echo ""
    echo "  # Using formating function:"
    echo "  formating success \"It works!\""
    echo "  formating warning \"Check this\""
    echo "  formating error \"Failed to load\""
    echo ""
    echo "Code Examples:"
    echo ""
    echo "  # In your scripts:"
    echo "  if test -f myfile.txt"
    echo "    success \"File found!\""
    echo "  else"
    echo "    error \"File not found!\""
    echo "  end"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
end
